# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('houseinfo', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('finish', models.CharField(max_length=10)),
                ('house_type', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
